# this playbook configures a bgp neighborship
# between the spine switches of the PNI
---
- name: bgp_r1_play
  hosts: bgp_as_65111 
  vars:
          ansible_user: admin
          ansible_ssh_pass: YourPaSsWoRd
          eth20_ip: 192.168.1.1/32
          router_id: 1.1.1.1
          neighbor_ip: 192.168.1.2
          bgp_asn: 65111
          neighbor_bgp_asn: 65222
  become: true
  gather_facts: false
  tasks:
          - name: setup bgp interface
            command: |
                    vtysh -c
                    "
                     config
                     interface Ethernet20
                     ip address {{eth20_ip}}
                     no shutdown
                     end
                    "

          - name: configure BGP neighborship
            command: |
                    vtysh -c
                    "
                     config
                     router-id {{router_id}}
                     router bgp {{bgp_asn}}
                     neighbor {{neighbor_ip}} remote-as {{neighbor_bgp_asn}}
                    "
          
          - name: save running config
            command: |
                vtysh -c
                "
                 write memory
                "
- name: bgp_r2_play
  hosts: bgp_as_65222 
  vars:
          ansible_user: admin
          ansible_ssh_pass: YourPaSsWoRd
          eth20_ip: 192.168.1.2/32
          router_id: 2.2.2.2
          neighbor_ip: 192.168.1.1
          bgp_asn: 65222
          neighbor_bgp_asn: 65111
  become: true
  gather_facts: false
  tasks:
          - name: setup bgp interface
            command: |
                    vtysh -c
                    "
                    config
                    interface Ethernet20
                    ip address {{eth20_ip}}
                    no shutdown
                    end
                    "
          
          - name: configure BGP neighborship
            command: |
                    vtysh -c
                    "
                    config
                    router-id {{router_id}}
                    router bgp {{bgp_asn}}
                    neighbor {{neighbor_ip}} remote-as {{neighbor_bgp_asn}}
                    "
          
          - name: save running config
            command: |
                vtysh -c
                "
                write memory
                "
