---
- hosts: all
  vars:
          ansible_user: admin
          ansible_ssh_pass: YourPaSsWoRd
  become: true
  gather_facts: true
  tasks:
          - name: enable bgp on all interfaces
            command: config bgp startup all
          
          - name: save running config
            command: config save -y
